import { writeFileSync } from "fs";

const USER = "keybodhi";
const TOKEN = process.env.GITHUB_TOKEN || "";
const headers = { "Accept": "application/vnd.github+json" };
if (TOKEN) headers.Authorization = `token ${TOKEN}`;

const api = async (path) => {
  const res = await fetch(`https://api.github.com${path}`, { headers });
  if (!res.ok) throw new Error(`${path}: ${res.status}`);
  return res.json();
};

const LANGS = [
  ["C++", "#00E5FF"],
  ["C", "#3AA6DD"],
  ["C#", "#FF00FF"],
  ["TypeScript", "#00B0FF"],
  ["JavaScript", "#FFD700"],
  ["Python", "#7B68EE"],
  ["HTML", "#FF6B6B"],
  ["CSS", "#4DD0E1"],
  ["Rust", "#FFA500"],
  ["Lua", "#FF8C00"],
  ["Shell", "#90EE90"],
  ["Java", "#FF7043"],
  ["Go", "#26C6DA"],
  ["PHP", "#AB47BC"],
];

const langColor = (lang) => {
  const hit = LANGS.find(([n]) => n === lang);
  if (hit) return hit[1];
  const hash = [...lang].reduce((a, c) => a + c.charCodeAt(0), 0);
  const palette = ["#9E9E9E", "#B0BEC5", "#80CBC4", "#BCAAA4", "#A5D6A7", "#CE93D8", "#90CAF9"];
  return palette[hash % palette.length];
};

const fmtBytes = (b) => {
  if (b >= 1e9) return (b / 1e9).toFixed(1) + " GB";
  if (b >= 1e6) return (b / 1e6).toFixed(1) + " MB";
  if (b >= 1e3) return (b / 1e3).toFixed(1) + " KB";
  return b + " B";
};

const esc = (s) => s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");

const DEFS = `
<defs>
  <linearGradient id="neon" x1="0%" y1="0%" x2="100%" y2="0%">
    <stop offset="0%" stop-color="#00E5FF"/>
    <stop offset="50%" stop-color="#FF00FF"/>
    <stop offset="100%" stop-color="#00E5FF"/>
  </linearGradient>
  <linearGradient id="border" x1="0%" y1="0%" x2="100%" y2="100%">
    <stop offset="0%" stop-color="#00E5FF" stop-opacity="0.5"/>
    <stop offset="100%" stop-color="#FF00FF" stop-opacity="0.5"/>
  </linearGradient>
</defs>`;

const statsSvg = (data) => {
  const rows = [
    ["Stars", String(data.stars)],
    ["Forks", String(data.forks)],
    ["Public repos", String(data.repos)],
    ["Followers", String(data.followers)],
    ["Following", String(data.following)],
    ["Code", fmtBytes(data.codeBytes)],
  ];
  const rowH = 27;
  const inner = rows
    .map(([k, v], i) => {
      const y = 62 + i * rowH;
      return `<text x="28" y="${y}" font-family="Segoe UI, Arial, sans-serif" font-size="13.5" fill="#7f8db0">${esc(k)}</text>
<text x="354" y="${y}" text-anchor="end" font-family="Segoe UI, Arial, sans-serif" font-size="15" font-weight="600" fill="#00E5FF">${esc(v)}</text>`;
    })
    .join("\n");
  return `<svg xmlns="http://www.w3.org/2000/svg" width="382" height="${62 + rows.length * rowH + 16}" viewBox="0 0 382 ${62 + rows.length * rowH + 16}">
  ${DEFS}
  <rect x="1" y="1" width="380" height="${60 + rows.length * rowH + 14}" rx="10" fill="#0D0E17" stroke="url(#border)" stroke-width="2"/>
  <text x="191" y="38" text-anchor="middle" font-family="Segoe UI, Arial, sans-serif" font-size="17" font-weight="700" letter-spacing="4" fill="url(#neon)">GITHUB STATS</text>
${inner}
  <text x="191" y="${62 + rows.length * rowH + 6}" text-anchor="middle" font-family="Segoe UI, Arial, sans-serif" font-size="9.5" fill="#3d4663">generated by GitHub Actions · keybodhi</text>
</svg>`;
};

const langsSvg = (langs) => {
  const W = 382;
  const PAD = 24;
  const titleH = 56;
  const rowH = 30;
  const barW = W - PAD * 2;
  const total = langs.reduce((a, [, v]) => a + v, 0) || 1;
  const shown = langs.slice(0, 8);
  const H = titleH + shown.length * rowH + 14;
  const rows = shown
    .map(([name, bytes], i) => {
      const y = titleH + 16 + i * rowH;
      const pct = Math.round((bytes / total) * 1000) / 10;
      const w = Math.max(2, Math.round((barW * bytes) / total));
      return `<text x="${PAD}" y="${y}" font-family="Segoe UI, Arial, sans-serif" font-size="13" fill="#c8d3f0">${esc(name)}</text>
<text x="${W - PAD}" y="${y}" text-anchor="end" font-family="Segoe UI, Arial, sans-serif" font-size="13" font-weight="600" fill="#00E5FF">${pct}%</text>
<rect x="${PAD}" y="${y + 8}" width="${barW}" height="7" rx="3.5" fill="#1E2440"/>
<rect x="${PAD}" y="${y + 8}" width="${w}" height="7" rx="3.5" fill="${langColor(name)}"/>`;
    })
    .join("\n");
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${H}" viewBox="0 0 ${W} ${H}">
  ${DEFS}
  <rect x="1" y="1" width="${W - 2}" height="${H - 2}" rx="10" fill="#0D0E17" stroke="url(#border)" stroke-width="2"/>
  <text x="${W / 2}" y="34" text-anchor="middle" font-family="Segoe UI, Arial, sans-serif" font-size="17" font-weight="700" letter-spacing="4" fill="url(#neon)">TOP LANGUAGES</text>
${rows}
</svg>`;
};

const user = await api(`/users/${USER}`);
const repos = await api(`/users/${USER}/repos?per_page=100&sort=updated&type=all`);

let stars = 0;
let forks = 0;
const langBytes = {};
for (const r of repos) {
  if (r.fork) continue;
  stars += r.stargazers_count;
  forks += r.forks_count;
  const langs = await api(`/repos/${USER}/${r.name}/languages`);
  for (const [lang, bytes] of Object.entries(langs)) {
    langBytes[lang] = (langBytes[lang] || 0) + bytes;
  }
}

const codeBytes = Object.values(langBytes).reduce((a, b) => a + b, 0);
const langs = Object.entries(langBytes).sort((a, b) => b[1] - a[1]);

writeFileSync("assets/stats.svg", statsSvg({ stars, forks, repos: user.public_repos, followers: user.followers, following: user.following, codeBytes }));
writeFileSync("assets/top-langs.svg", langsSvg(langs));
console.log("stats.svg + top-langs.svg generated");
console.log(`stars=${stars} forks=${forks} repos=${user.public_repos} langs=${langs.length} codeBytes=${codeBytes}`);
